### ISSUE TITLE
Hang at "Sending ping to Max."

### ISSUE THREAD

**Issue by cassiel** [Cycling74/max-test#13]
This is a bit sporadic, although on my El Capitan machine I have one checkout of max-test which always works and another which always fails. On my Sierra machine it always fails.

In Sierra, the process runs - very slowly - for a while. See screenshot. The last meaningful message is:

`[0901/184516:WARNING:dns_config_service_posix.cc(217)] Failed to read DnsConfig.`

(That's nearly an hour into the running time.)

![screenshot 2016-09-02 08 56 18](https://cloud.githubusercontent.com/assets/658505/18196767/695fc1e0-70eb-11e6-80bc-46e3f0074535.png)

**Comment by cassiel** [comment]
Pilot error: wasn't setting up the oscar ports...

**Comment by cassiel** [comment]
Actually, taking that back: have now dropped in the oscar config, no change.

**Comment by tap** [comment]
@cassiel if the `oscar` extension is loaded and the config file is found then there should be output to the console from Max that says so and says which ports it is using.  Do you see that in your console output?

**Comment by cassiel** [comment]
Let me A/B test this in my two environments and see what gets printed.

**Comment by benbrackenc74** [comment]
assuming this is no longer an issue
