### ISSUE TITLE
How to build max-test for 64-bit Windows ?

### ISSUE THREAD

**Issue by jsln** [Cycling74/max-test#15]
Hi all,

anybody has instructions on how to build max-test for 64-bit Windows? I am using VS2017 but I have progressed very little.

Regards,
Juan.

**Comment by tap** [comment]
Hi Juan,

With the commits of the last couple of days, the oscar extension should build properly for 64-bit windows. I just tested this using VS2017 on Windows 10.

Hope this helps!
