### ISSUE TITLE
Max hangs until mouse moves

### ISSUE THREAD

**Issue by cassiel** [Cycling74/max-test#6]
It seems that the test process hangs when first opening Max, until I focus and move the mouse pointer in one of Max's windows. Then it runs to completion.

OS X 10.11.6.

**Comment by tap** [comment]
Hi Nick -- I think this should be "fixed" (as in a silly workaround) as of earlier today in 84ff6266e44eb750a418512eefc0e3c1d2d2f2f2

**Comment by cassiel** [comment]
Thanks. It seems that Max gets successfully unhung by mouse activity even if not front-most; but I'll roll in this fix anyway and see how it goes.

**Comment by cassiel** [comment]
OK - improvement with this patch, but Max still hangs part-way through the process, requiring mouse-move to kick it back into action. (Hangs on a specific MXJ test, so I wonder if there's something in that.)

**Comment by tap** [comment]
Strange.  (sigh)  I wonder what is causing that.

best,
  Tim

**Comment by cassiel** [comment]
Comes and goes. (Also sometimes it hangs on the same patcher with pizza-of-death.) Will try to determine the specific conditions. Might the patcher scripting be something to do with it? (I notice that it hangs before it's scripted the new object into place, and then on mouse-move the scripted object immediately appears.)

**Comment by tap** [comment]
oh -- interesting!  that sounds very plausible!  maybe the patcher
scripting can be replaced by using a pcontrol to open another patcher to
find out.

best,
  Tim

**Comment by cassiel** [comment]
OK - let me try to instrument/isolate that.

More generally: is it possible to put something into the Ruby script to time out these things and force-relaunch Max if needed? Would that bork the SQLite logging?
